package com.shindefirm.shopapp.web_service;

public enum MethodOrdinal {
    DO_LOGIN_OR_REGISTER, GET_VILLAGE, GET_DISTRICT, GET_TALUKA, GET_OTP,GET_RESEND_OTP,
    GET_KARYAKARTA, GET_GENERAL_DATA, GET_CITY, POST_UPDATE_PROFILE, POST_UPDATE_PROFILE_PHOTO,
    INSERT_FEEDBACK, GET_PROGRAM_LIST, GET_ACTIVITY_DATA_BY_USER_ID, GET_ACTIVITY_DATA_BY_ID,
    POST_INSERT_ACTIVITY,POST_INSERT_FORWARD_ACTIVITY, POST_UPLOAD_ACTIVITY_PHOTO,
    POST_UPLOAD_FORWARD_ACTIVITY_PHOTO, POST_DELETE_ACTIVITY_PHOTO,
    POST_DELETE_FORWARD_ACTIVITY_PHOTO,POST_FORWARDED_ACTIVITY,POST_NOTIFICATION_ACTIVITY,
    POST_REMOVE_UPDATE_PROFILE,GET_CONSTITUENCY,GET_LIKES,INSERT_LIKES,GET_COMMENTS,
    INSERT_COMMENTS,DELETE_COMMENTS, GET_TWITTER,POST_DELETE_ACTIVITY, GET_CHAT_MESSAGE,
    POST_INSERT_CHAT_MESSAGE, GET_CHAT_MESSAGE_BY_GROUP_ID, POST_MARKED_AS_READ_ALL_MESSAGE,
    GET_ALL_GROUP_OF_CHAT, POST_UPLOAD_MEDIA_IN_CHAT,INSERT_SHARE_ACTIVITY_USAGE,GET_SLIDER_IMAGES
}